-- ForgeFit platform legal acceptance foundation
-- Draft version: 2026-09-04-beta. Run in Supabase SQL Editor after attorney review.

create table if not exists public.platform_legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  source text not null default 'signup',
  constraint platform_legal_acceptances_version_check
    check (char_length(terms_version) between 1 and 100 and char_length(privacy_version) between 1 and 100)
);

create unique index if not exists platform_legal_acceptances_unique_version
  on public.platform_legal_acceptances (user_id, terms_version, privacy_version);

alter table public.platform_legal_acceptances enable row level security;
revoke all on public.platform_legal_acceptances from anon;
revoke all on public.platform_legal_acceptances from authenticated;
grant select on public.platform_legal_acceptances to authenticated;

drop policy if exists "Members can view their legal acceptances" on public.platform_legal_acceptances;
create policy "Members can view their legal acceptances"
  on public.platform_legal_acceptances for select to authenticated
  using (user_id = auth.uid());

create or replace function public.record_signup_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $function$
declare
  accepted boolean := coalesce((new.raw_user_meta_data->>'platform_legal_accepted')::boolean, false);
begin
  if accepted then
    insert into public.platform_legal_acceptances
      (user_id, terms_version, privacy_version, accepted_at, source)
    values (
      new.id,
      coalesce(nullif(new.raw_user_meta_data->>'terms_version',''), 'unknown'),
      coalesce(nullif(new.raw_user_meta_data->>'privacy_version',''), 'unknown'),
      coalesce((new.raw_user_meta_data->>'legal_accepted_at')::timestamptz, now()),
      'signup'
    )
    on conflict (user_id, terms_version, privacy_version) do nothing;
  end if;
  return new;
end;
$function$;

revoke all on function public.record_signup_legal_acceptance() from public, anon, authenticated;

drop trigger if exists on_auth_user_record_legal_acceptance on auth.users;
create trigger on_auth_user_record_legal_acceptance
  after insert on auth.users
  for each row execute function public.record_signup_legal_acceptance();
